// a list of all css properties that take in a color value, in their regular form
export const colorRules = [
  'color',
  'background',
  'background-color',
  'border',
  'border-top',
  'border-right',
  'border-bottom',
  'border-left',
  'border-color',
  'border-top-color',
  'border-right-color',
  'border-bottom-color',
  'border-left-color',
  'outline',
  'outline-color',
  'text-decoration',
  'text-decoration-color',
  'text-emphasis',
  'text-emphasis-color',
  'text-shadow',
  'box-shadow',
  'fill',
  'stroke',
  'caret-color',
  'column-rule',
  'column-rule-color',
  'text-fill-color',
]

export const spacingRules = [
  'gap',
  'margin',
  'margin-top',
  'margin-right',
  'margin-bottom',
  'margin-left',
  'padding',
  'padding-top',
  'padding-right',
  'padding-bottom',
  'padding-left',
  'grid-gap',
  'letter-spacing',
]
